"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "../../../components/AppShell";
import { apiFetch, newOpId } from "../../../lib/api";
import { HISTORICAL_IMPORT_ROLES, PAYMENT_ROLES, canAccess, type PublicUser } from "@stoneos/contracts";

type Bill = { id:string; kind:string; reference:string; partyName:string; occurredOn:string; materialAmount:string; customerAdjustment:string; gstAmount:string; outstanding:number; stockStatus:string; payload:{note:string; lines:Array<{variety:string;sqft?:number;serial?:string;weightTons?:number;rate?:number}>}; settlements:Array<{amount:string;occurredOn:string;payload:{kind:string;account:string;note?:string}}> };
const inr = (n:number|string) => Number(n).toLocaleString("en-IN",{style:"currency",currency:"INR"});
const today = () => new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
const blankLine = () => ({variety:"",sqft:"",rate:"",serial:"",weightTons:"",stage:"finished"});
const blankPayment = () => ({kind:"funds",account:"Cash",amount:"",note:""});
export default function TradesPage() {
  const [me,setMe]=useState<PublicUser|null>(null),[bills,setBills]=useState<Bill[]>([]),[accounts,setAccounts]=useState<Array<{name:string;balance:number}>>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [kind,setKind]=useState("local_sale"),[reference,setReference]=useState(""),[party,setParty]=useState(""),[day,setDay]=useState(today),[material,setMaterial]=useState(""),[adjustment,setAdjustment]=useState("0"),[gst,setGst]=useState("0"),[invoiceTaxable,setInvoiceTaxable]=useState("0"),[gstin,setGstin]=useState(""),[royalty,setRoyalty]=useState("0"),[transport,setTransport]=useState("0"),[commission,setCommission]=useState("0"),[cashAdjustment,setCashAdjustment]=useState("0"),[note,setNote]=useState("");
  const [lines,setLines]=useState([blankLine()]),[payments,setPayments]=useState<ReturnType<typeof blankPayment>[]>([]),[op,setOp]=useState("");
  const [selected,setSelected]=useState(""),[later,setLater]=useState(blankPayment),[laterDay,setLaterDay]=useState(today),[laterOp,setLaterOp]=useState("");
  async function refresh(){ const [b,a]=await Promise.all([apiFetch<Bill[]>("/api/v1/books/trades"),apiFetch<Array<{name:string;balance:number}>>("/api/v1/books/trades/accounts")]);setBills(b.filter(x=>x.kind!=="ledger_sale"));setAccounts(a); }
  useEffect(()=>{apiFetch<PublicUser>("/api/v1/auth/me").then(setMe).catch(e=>setError(e.message));refresh().catch(e=>setError(e.message));setOp(newOpId());setLaterOp(newOpId());},[]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{
    const body={kind,reference,partyName:party,date:day,materialAmount:Number(material),customerAdjustment:kind==="local_sale"?Number(adjustment):0,gstAmount:kind==="raw_purchase"?Number(gst):0,invoiceTaxable:kind==="raw_purchase"?Number(invoiceTaxable):0,...(gstin&&kind==="raw_purchase"?{supplierGstin:gstin}:{}),royalty:kind==="raw_purchase"?Number(royalty):0,transport:kind==="raw_purchase"?Number(transport):0,commission:kind==="local_sale"?Number(commission):0,collectionCashAdjustment:kind==="local_sale"?Number(cashAdjustment):0,note,clientOpId:op,lines:lines.map(l=>kind==="local_sale"?{variety:l.variety,sqft:Number(l.sqft),rate:Number(l.rate),stage:l.stage}:{variety:l.variety,serial:l.serial,weightTons:Number(l.weightTons)}),payments:payments.map(p=>({...p,amount:Number(p.amount)}))};
    await apiFetch("/api/v1/books/trades",{method:"POST",body:JSON.stringify(body),onlineOnly:true});setOp(newOpId());setReference("");setPayments([]);setMessage("Bill posted. Its account entries are available in Books.");await refresh();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function pay(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await apiFetch(`/api/v1/books/trades/${selected}/payments`,{method:"POST",body:JSON.stringify({date:laterDay,clientOpId:laterOp,payment:{...later,amount:Number(later.amount)}}),onlineOnly:true});setLaterOp(newOpId());setLater(blankPayment());setMessage("Payment recorded.");await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const edit=!!me&&canAccess(me.role,HISTORICAL_IMPORT_ROLES),canPay=!!me&&canAccess(me.role,PAYMENT_ROLES);
  function paymentFields(p:ReturnType<typeof blankPayment>,change:(p:ReturnType<typeof blankPayment>)=>void,purchase:boolean){return <div className="grid">
    <label>Settlement type<select value={p.kind} onChange={e=>change({...p,kind:e.target.value})}><option value="funds">Cash / bank / PhonePe</option>{!purchase&&<><option value="creditor">Paid directly to our creditor</option><option value="vendor_advance">Paid as vendor advance</option><option value="customer_advance">Apply recorded customer advance</option></>}</select></label>
    <label>Account or vendor<input list="fund-accounts" value={p.account} onChange={e=>change({...p,account:e.target.value})} required/></label>
    <label>Amount ₹<input type="number" min="0.01" step="0.01" value={p.amount} onChange={e=>change({...p,amount:e.target.value})} required/></label>
    <label>Payment note<input value={p.note} onChange={e=>change({...p,note:e.target.value})}/></label></div>;}
  return <AppShell><h1>Local sales &amp; raw purchases</h1><p><Link href="/books">Back to Books</Link></p><p>Local sales carry no GST. Record the agreed material value and the actual settlement accounts. Unallocated sale quantities remain visible until their dispatch lots are identified.</p>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <datalist id="fund-accounts"><option value="Cash"/>{accounts.map(a=><option key={a.name} value={a.name}/>)}</datalist>
    <details><summary>Cash, bank and PhonePe balances</summary><div className="table-wrap"><table><thead><tr><th>Account</th><th>Balance</th></tr></thead><tbody>{accounts.map(a=><tr key={a.name}><td>{a.name}</td><td>{inr(a.balance)}</td></tr>)}</tbody></table></div></details>
    {edit&&<details><summary>Add a bill</summary><form onSubmit={save}><div className="grid">
      <label>Bill type<select value={kind} onChange={e=>{setKind(e.target.value);setPayments([]);setLines([blankLine()]);}}><option value="local_sale">Local sale — no GST</option><option value="raw_purchase">Raw block purchase</option></select></label>
      <label>Slip / invoice number<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><label>{kind==="local_sale"?"Customer":"Supplier"}<input value={party} onChange={e=>setParty(e.target.value)} required/></label><label>Business date<input type="date" value={day} max={today()} onChange={e=>setDay(e.target.value)} required/></label>
      <label>Agreed material value ₹<input type="number" min="0.01" step="0.01" value={material} onChange={e=>setMaterial(e.target.value)} required/></label>
      {kind==="local_sale"?<><label>Additional non-material customer dues ₹<input type="number" min="0" step="0.01" value={adjustment} onChange={e=>setAdjustment(e.target.value)}/></label><label>Cash sales commission paid ₹<input type="number" min="0" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)}/></label><label>Non-material collection paid from cash ₹<input type="number" min="0" step="0.01" value={cashAdjustment} onChange={e=>setCashAdjustment(e.target.value)}/></label></>:<>
      <label>Supplier invoice value before GST ₹<input type="number" min="0" step="0.01" value={invoiceTaxable} onChange={e=>setInvoiceTaxable(e.target.value)}/></label><label>GST from supplier invoice ₹<input type="number" min="0" step="0.01" value={gst} onChange={e=>setGst(e.target.value)}/></label><label>Supplier GSTIN<input value={gstin} onChange={e=>setGstin(e.target.value)}/></label><label>Royalty paid in cash ₹<input type="number" min="0" step="0.01" value={royalty} onChange={e=>setRoyalty(e.target.value)}/></label><label>Inward transport paid in cash ₹<input type="number" min="0" step="0.01" value={transport} onChange={e=>setTransport(e.target.value)}/></label></>}
    </div><p>Material details</p>{lines.map((l,i)=><div className="grid" key={i}><label>Variety<input value={l.variety} required onChange={e=>setLines(lines.map((x,j)=>i===j?{...x,variety:e.target.value}:x))}/></label>{(kind==="local_sale"?["sqft","rate"]:["serial","weightTons"]).map(k=><label key={k}>{({sqft:"Sqft",rate:"Rate ₹",serial:"Block number",weightTons:"Weight tonnes"} as Record<string,string>)[k]}<input required type={k==="serial"?"text":"number"} min="0" step="any" value={l[k as keyof typeof l]} onChange={e=>setLines(lines.map((x,j)=>i===j?{...x,[k]:e.target.value}:x))}/></label>)}<button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>i!==j))}>Remove material</button></div>)}<button type="button" onClick={()=>setLines([...lines,blankLine()])}>Add material</button>
    <p>Payments already made / received. Leave empty for a fully unpaid bill.</p>{payments.map((p,i)=><div key={i}>{paymentFields(p,v=>setPayments(payments.map((x,j)=>i===j?v:x)),kind==="raw_purchase")}<button type="button" onClick={()=>setPayments(payments.filter((_,j)=>i!==j))}>Remove payment</button></div>)}<button type="button" onClick={()=>setPayments([...payments,blankPayment()])}>Add payment</button><label>Bill note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy}>Post bill</button></form></details>}
    {canPay&&<details><summary>Record a later payment</summary><form id="trade-payment" onSubmit={pay}><label>Bill<select aria-label="Outstanding bill" value={selected} required onChange={e=>setSelected(e.target.value)}><option value="">Choose outstanding bill</option>{bills.filter(b=>b.outstanding>0).map(b=><option key={b.id} value={b.id}>{b.reference} — {b.partyName} — {inr(b.outstanding)}</option>)}</select></label><label>Payment date<input type="date" value={laterDay} max={today()} onChange={e=>setLaterDay(e.target.value)}/></label>{paymentFields(later,setLater,bills.find(b=>b.id===selected)?.kind==="raw_purchase")}<button disabled={busy}>Record payment</button></form></details>}
    <div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference / party</th><th>Material value</th><th>Other dues / GST</th><th>Outstanding</th><th>Stock</th></tr></thead><tbody>{bills.map(b=><tr key={b.id}><td>{b.occurredOn.slice(0,10)}</td><td><details><summary>{b.reference} — {b.partyName}</summary><p>{b.kind==="local_sale"?"Local sale — no GST":"Raw purchase"}</p>{b.payload.lines.map((l,i)=><p key={i}>{l.variety} — {l.serial?`Block ${l.serial}, ${l.weightTons} tonnes`:`${l.sqft ?? "Quantity pending"} sqft @ ${inr(l.rate??0)}`}</p>)}<p>{b.payload.note}</p>{b.settlements.map((p,i)=><p key={i}>{p.occurredOn.slice(0,10)} · {p.payload.account} · {inr(p.amount)} · {p.payload.note}</p>)}</details></td><td>{inr(b.materialAmount)}</td><td>{inr(Number(b.customerAdjustment)+Number(b.gstAmount))}</td><td>{inr(b.outstanding)}</td><td>{b.stockStatus==="received"?"Blocks received":"Dispatch lot allocation pending"}</td></tr>)}</tbody></table></div>
  </AppShell>;
}
