import {expect,test} from "@playwright/test";
test.use({serviceWorkers:"block"});
for(const width of [390,1280])test(`manual sale review, posting and later receipt at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.addInitScript(()=>localStorage.setItem("stoneos.token","fixture"));let bills:any[]=[];
 await page.route("**/api/v1/**",async route=>{const u=new URL(route.request().url()).pathname;const method=route.request().method();
 if(u.endsWith("/auth/me"))return route.fulfill({json:{id:"owner",factoryId:"factory",role:"owner",mustChangePassword:false}});
 if(u.endsWith("/ledger-sales"))return route.fulfill({json:{documents:bills,legacy:[]}});
 if(u.endsWith("/accounts"))return route.fulfill({json:[{name:"Cash",balance:0}]});
 if(u.endsWith("/books/trades")&&method==="POST"){const b=route.request().postDataJSON();expect(b).toMatchObject({kind:"ledger_sale",materialAmount:1000,customerAdjustment:50,gstAmount:180,gstHead:"igst",payments:[],collectionPlan:{cash:300,bank:0}});bills=[{...b,id:"bill",occurredOn:b.date,outstanding:1230,payload:b,settlements:[]}];return route.fulfill({json:bills[0]});}
 if(u.endsWith("/bill/payments")){expect(route.request().postDataJSON().payment).toMatchObject({account:"Cash",amount:300,note:"Received today"});bills[0].outstanding=930;return route.fulfill({json:{id:"payment"}});}
 return route.fulfill({json:[]});});
 await page.goto("/books/ledger-sales");await page.getByLabel("Customer",{exact:true}).fill("Training buyer");await page.getByLabel("Sale / invoice reference").fill("T-1");await page.getByLabel("Variety",{exact:true}).fill("Black");await page.getByLabel("Sqft",{exact:true}).fill("10");await page.getByLabel("Rate ₹",{exact:true}).fill("100");await page.getByLabel("Loading income ₹").fill("50");await page.getByLabel("GST head").selectOption("igst");await page.getByLabel("Supplied GST ₹").fill("180");await page.getByLabel("Cash planned ₹").fill("300");await page.getByRole("button",{name:"Review sale",exact:true}).click();await expect(page.getByRole("heading",{name:"Review before posting"})).toBeVisible();await expect(page.getByLabel("Customer",{exact:true})).toBeDisabled();await page.getByRole("button",{name:"Post sale",exact:true}).click();await expect(page.getByRole("status")).toContainText("Sale posted");await page.getByLabel("Outstanding sale").selectOption("bill");await page.getByLabel("Received amount ₹").fill("300");await page.getByLabel("Payment note").fill("Received today");await page.getByRole("button",{name:"Record payment",exact:true}).click();await expect(page.getByRole("status")).toContainText("Payment recorded");
});
test("existing entry is linked through review and no second sale request is made",async({page})=>{
 await page.addInitScript(()=>localStorage.setItem("stoneos.token","fixture"));let posted=false;
 const legacy={voucherId:"prior",partyId:"party",partyName:"Earlier buyer",reference:"OLD-1",date:"2026-10-01",materialAmount:1000,customerAdjustment:50,gstAmount:180,gstHead:"igst",lines:[{variety:"Black",sqft:10,rate:100}],note:"Existing source",collectionPlan:{cash:0,bank:0,note:""}};
 await page.route("**/api/v1/**",async route=>{const u=new URL(route.request().url()).pathname;if(u.endsWith("/auth/me"))return route.fulfill({json:{id:"owner",factoryId:"factory",role:"owner"}});if(u.endsWith("/ledger-sales"))return route.fulfill({json:{documents:[],legacy:posted?[]:[legacy]}});if(route.request().method()==="POST"){expect(route.request().postDataJSON()).toMatchObject({legacyVoucherId:"prior",materialAmount:1000,customerAdjustment:50,gstAmount:180,payments:[]});posted=true;return route.fulfill({json:{id:"linked"}});}return route.fulfill({json:[]});});
 await page.goto("/books/ledger-sales");await page.getByRole("button",{name:"Review and link existing entry"}).click();await page.getByRole("button",{name:"Review sale",exact:true}).click();await page.getByRole("button",{name:"Link existing sale",exact:true}).click();await expect(page.getByRole("status")).toContainText("No debt or cash was posted again");expect(posted).toBe(true);
});