"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AppShell} from "../../../components/AppShell";
import {apiFetch,newOpId} from "../../../lib/api";
import {canAccess,HISTORICAL_IMPORT_ROLES,PAYMENT_ROLES,type PublicUser} from "@stoneos/contracts";

type Line={variety:string;sqft:string;rate:string};
type Payload={note:string;gstHead:string;lines:Array<{variety:string;sqft:number;rate:number}>;printedInvoice?:{taxable:number;gst:number;total:number;sqft:number};collectionPlan?:{cash:number;bank:number;note:string};legacyVoucherId?:string};
type Bill={id:string;reference:string;partyName:string;occurredOn:string;materialAmount:string;customerAdjustment:string;gstAmount:string;outstanding:number;payload:Payload;settlements:Array<{amount:string;occurredOn:string;payload:{account:string;note?:string}}>};
type Legacy=Omit<Payload,"lines">&{voucherId:string;partyId:string;partyName:string;reference:string;date:string;materialAmount:number;gstAmount:number;customerAdjustment:number;lines:Array<{variety:string;sqft:number;rate:number}>};
const rupees=(n:number|string)=>Number(n).toLocaleString("en-IN",{style:"currency",currency:"INR"});
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
const blank=():Line=>({variety:"",sqft:"",rate:""});
export default function LedgerSalesPage(){
 const [me,setMe]=useState<PublicUser|null>(null),[bills,setBills]=useState<Bill[]>([]),[legacy,setLegacy]=useState<Legacy[]>([]),[customers,setCustomers]=useState<string[]>([]),[accounts,setAccounts]=useState<string[]>([]);
 const [party,setParty]=useState(""),[reference,setReference]=useState(""),[day,setDay]=useState(today),[lines,setLines]=useState<Line[]>([blank()]),[loading,setLoading]=useState("0"),[gstHead,setHead]=useState("none"),[gst,setGst]=useState("0"),[note,setNote]=useState("");
 const [printed,setPrinted]=useState(false),[taxable,setTaxable]=useState("0"),[printedGst,setPrintedGst]=useState("0"),[printedTotal,setPrintedTotal]=useState("0"),[printedSqft,setPrintedSqft]=useState("0"),[cashPlan,setCashPlan]=useState("0"),[bankPlan,setBankPlan]=useState("0"),[planNote,setPlanNote]=useState(""),[linkId,setLinkId]=useState("");
 const [op,setOp]=useState(""),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [payBill,setPayBill]=useState(""),[payAmount,setPayAmount]=useState(""),[payAccount,setPayAccount]=useState("Cash"),[payDay,setPayDay]=useState(today),[payNote,setPayNote]=useState(""),[payOp,setPayOp]=useState("");
 const edit=!!me&&canAccess(me.role,HISTORICAL_IMPORT_ROLES),canPay=!!me&&canAccess(me.role,PAYMENT_ROLES);
 const material=lines.reduce((n,l)=>n+Math.round(Number(l.sqft)*Number(l.rate)*100),0)/100;
 const total=Math.round((material+Number(loading)+Number(gst))*100)/100;
 const mismatch=printed&&(Math.round(Number(taxable)*100)!==Math.round(material*100)||Number(printedSqft)!==lines.reduce((n,l)=>n+Number(l.sqft),0));
 async function refresh(){const d=await apiFetch<{documents:Bill[];legacy:Legacy[]}>("/api/v1/books/trades/ledger-sales");setBills(d.documents);setLegacy(d.legacy);}
 useEffect(()=>{setOp(newOpId());setPayOp(newOpId());apiFetch<PublicUser>("/api/v1/auth/me").then(setMe).catch(e=>setError(e.message));refresh().catch(e=>setError(e.message));apiFetch<Array<{name:string}>>("/api/v1/customers").then(c=>setCustomers(c.map(x=>x.name))).catch(()=>undefined);apiFetch<Array<{name:string}>>("/api/v1/books/trades/accounts").then(c=>setAccounts(c.map(x=>x.name))).catch(()=>undefined);},[]);
 function reset(){setParty("");setReference("");setLines([blank()]);setLoading("0");setHead("none");setGst("0");setNote("");setPrinted(false);setCashPlan("0");setBankPlan("0");setPlanNote("");setLinkId("");setReview(false);setOp(newOpId());}
 function link(l:Legacy){setParty(l.partyName);setReference(l.reference);setDay(l.date);setLines(l.lines.map(x=>({variety:x.variety,sqft:String(x.sqft),rate:String(x.rate)})));setLoading(String(l.customerAdjustment));setGst(String(l.gstAmount));setHead(l.gstHead);setNote(l.note);setPrinted(!!l.printedInvoice);if(l.printedInvoice){setTaxable(String(l.printedInvoice.taxable));setPrintedGst(String(l.printedInvoice.gst));setPrintedTotal(String(l.printedInvoice.total));setPrintedSqft(String(l.printedInvoice.sqft));}setCashPlan(String(l.collectionPlan?.cash??0));setBankPlan(String(l.collectionPlan?.bank??0));setPlanNote(l.collectionPlan?.note??"");setLinkId(l.voucherId);setReview(false);setOp(newOpId());document.getElementById("ledger-entry")?.scrollIntoView({behavior:"smooth"});}
 function validate(){if(!party.trim()||!reference.trim()||!material||lines.some(l=>!l.variety.trim()||!(Number(l.sqft)>0)||!(Number(l.rate)>0)))return "Enter customer, reference, quantity and rate for every line.";if(Number(cashPlan)+Number(bankPlan)>total)return "Collection plan exceeds the total due.";if((gstHead==="none"&&Number(gst)!==0)||(gstHead!=="none"&&!(Number(gst)>0)))return "Check GST head and supplied tax amount.";if(printed&&Math.round((Number(taxable)+Number(printedGst))*100)!==Math.round(Number(printedTotal)*100))return "Printed invoice taxable value plus GST must equal its total.";if(mismatch&&!note.trim())return "Explain the printed invoice difference in notes.";return "";}
 async function post(){const issue=validate();if(issue){setError(issue);return;}setBusy(true);setError("");try{await apiFetch("/api/v1/books/trades",{method:"POST",onlineOnly:true,body:JSON.stringify({kind:"ledger_sale",partyName:party,reference,date:day,clientOpId:op,materialAmount:material,customerAdjustment:Number(loading),gstAmount:Number(gst),gstHead,note,lines:lines.map(l=>({variety:l.variety,sqft:Number(l.sqft),rate:Number(l.rate)})),payments:[],collectionPlan:{cash:Number(cashPlan),bank:Number(bankPlan),note:planNote},...(printed?{printedInvoice:{taxable:Number(taxable),gst:Number(printedGst),total:Number(printedTotal),sqft:Number(printedSqft)}}:{}),...(linkId?{legacyVoucherId:linkId}:{})})});setMessage(linkId?"Existing sale linked. No debt or cash was posted again.":"Sale posted. Customer debt updated; no money received or cash expense recorded.");reset();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await apiFetch(`/api/v1/books/trades/${payBill}/payments`,{method:"POST",onlineOnly:true,body:JSON.stringify({clientOpId:payOp,date:payDay,payment:{kind:"funds",account:payAccount,amount:Number(payAmount),note:payNote}})});setPayOp(newOpId());setPayAmount("");setPayNote("");setMessage("Payment recorded against the sale.");await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <AppShell><p><Link href="/books">← Books</Link></p><h1>Manual ledger sales</h1><p>Record a dated sale and full customer debt, with or without supplied GST. Loading income is separate from labour payments. This records the accounts; it does not generate a tax invoice or dispatch stock.</p>
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}
 <datalist id="ledger-customers">{customers.map(c=><option key={c} value={c}/>)}</datalist><datalist id="ledger-accounts">{accounts.map(c=><option key={c} value={c}/>)}</datalist>
 {edit&&<form id="ledger-entry" className="card" onSubmit={e=>{e.preventDefault();const issue=validate();setError(issue);if(!issue)setReview(true);}}><h2>{linkId?"Link existing entry":"Enter a sale"}</h2>{linkId&&<p>Review the existing figures. Linking keeps the original ledger voucher and balances.</p>}
 <fieldset disabled={review||busy}><div className="grid"><label>Customer<input list="ledger-customers" required value={party} onChange={e=>setParty(e.target.value)}/></label><label>Sale / invoice reference<input required value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Sale date<input type="date" required max={today()} value={day} onChange={e=>setDay(e.target.value)}/></label></div>
 {lines.map((l,i)=><fieldset key={i}><legend>Material {i+1}</legend><div className="grid"><label>Variety<input required value={l.variety} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,variety:e.target.value}:x))}/></label><label>Sqft<input required type="number" min="0.001" step="0.001" value={l.sqft} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,sqft:e.target.value}:x))}/></label><label>Rate ₹<input required type="number" min="0.01" step="0.01" value={l.rate} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,rate:e.target.value}:x))}/></label></div><p>Line amount: {rupees(Math.round(Number(l.sqft)*Number(l.rate)*100)/100)}</p>{lines.length>1&&<button type="button" className="secondary" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Remove material {i+1}</button>}</fieldset>)}
 <button type="button" className="secondary" onClick={()=>setLines([...lines,blank()])}>Add material</button><p>Material total: <strong>{rupees(material)}</strong></p>
 <div className="grid"><label>Loading income ₹<input type="number" min="0" step="0.01" value={loading} onChange={e=>setLoading(e.target.value)}/></label><label>GST head<select value={gstHead} onChange={e=>{setHead(e.target.value);if(e.target.value==="none")setGst("0");}}><option value="none">No supplied GST</option><option value="igst">IGST</option><option value="cgst_sgst">CGST + SGST equally</option></select></label><label>Supplied GST ₹<input type="number" min="0" step="0.01" value={gst} onChange={e=>setGst(e.target.value)}/></label></div><p>No labour payment is posted by this form. Enter cash expenses separately after checking the cash book.</p>
 <label><input type="checkbox" checked={printed} onChange={e=>setPrinted(e.target.checked)}/> Retain printed invoice figures</label>{printed&&<div className="grid"><label>Printed taxable value ₹<input type="number" min="0" step="0.01" value={taxable} onChange={e=>setTaxable(e.target.value)}/></label><label>Printed GST ₹<input type="number" min="0" step="0.01" value={printedGst} onChange={e=>setPrintedGst(e.target.value)}/></label><label>Printed total ₹<input type="number" min="0" step="0.01" value={printedTotal} onChange={e=>setPrintedTotal(e.target.value)}/></label><label>Printed sqft<input type="number" min="0" step="0.001" value={printedSqft} onChange={e=>setPrintedSqft(e.target.value)}/></label></div>}
 <label>Sale notes<textarea rows={4} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/></label><h3>Expected collection — no receipt</h3><div className="grid"><label>Cash planned ₹<input type="number" min="0" step="0.01" value={cashPlan} onChange={e=>setCashPlan(e.target.value)}/></label><label>Bank / UPI planned ₹<input type="number" min="0" step="0.01" value={bankPlan} onChange={e=>setBankPlan(e.target.value)}/></label></div><label>Collection plan note<input maxLength={1000} value={planNote} onChange={e=>setPlanNote(e.target.value)}/></label>
 </fieldset><p>Total customer debt: <strong>{rupees(total)}</strong></p>{!review&&<button type="submit" disabled={busy}>Review sale</button>}{review&&<section aria-label="Sale review"><h3>Review before posting</h3><p>{reference} · {party} · {day}</p><p>Material {rupees(material)} + loading income {rupees(loading)} + GST {rupees(gst)} = <strong>{rupees(total)}</strong></p><p>Received now: ₹0. Labour expense: not posted. Stock allocation: pending.</p>{mismatch&&<p role="alert">Printed figures differ. Full sale value remains visible; invoice and tax reconciliation is pending.</p>}<button type="button" disabled={busy} onClick={()=>setReview(false)}>Back to edit</button>{" "}<button type="button" disabled={busy} onClick={post}>{busy?"Saving…":linkId?"Link existing sale":"Post sale"}</button></section>}{linkId&&<button type="button" className="secondary" onClick={reset}>Cancel linking</button>}</form>}
 {legacy.length>0&&<section className="card"><h2>Previously recorded ledger entries</h2><p>These are already in Books. Link an entry to this register before using its payment form.</p>{legacy.map(l=><div key={l.voucherId}><p><strong>{l.reference} · {l.partyName}</strong> · {l.date} · {rupees(l.materialAmount+l.gstAmount+l.customerAdjustment)}</p><Link href={`/books/parties/${l.partyId}`}>View original statement</Link>{edit&&<> · <button type="button" onClick={()=>link(l)}>Review and link existing entry</button></>}</div>)}</section>}
 <section className="card"><h2>Recorded sales</h2>{!bills.length?<p>No sales linked to this register yet.</p>:bills.map(b=><details key={b.id}><summary>{b.reference} · {b.partyName} · Due {rupees(b.outstanding)}</summary><p>{b.occurredOn.slice(0,10)} · Material {rupees(b.materialAmount)} · Loading {rupees(b.customerAdjustment)} · GST {rupees(b.gstAmount)}</p>{b.payload.lines.map((l,i)=><p key={i}>{l.variety}: {l.sqft} sqft × {rupees(l.rate)}</p>)}<p>{b.payload.note}</p>{b.payload.printedInvoice&&<p>Printed source: taxable {rupees(b.payload.printedInvoice.taxable)} · GST {rupees(b.payload.printedInvoice.gst)} · total {rupees(b.payload.printedInvoice.total)} · {b.payload.printedInvoice.sqft} sqft. Retained separately for reconciliation.</p>}<p>Collection planned: cash {rupees(b.payload.collectionPlan?.cash??0)} · bank / UPI {rupees(b.payload.collectionPlan?.bank??0)}. {b.payload.collectionPlan?.note}</p><p>Dispatch lot allocation pending. No tax invoice generated.</p>{b.settlements.map((s,i)=><p key={i}>{s.occurredOn.slice(0,10)}: {rupees(s.amount)} · {s.payload.account} · {s.payload.note}</p>)}</details>)}</section>
 {canPay&&<form className="card" id="ledger-payment" onSubmit={pay}><h2>Record a received payment</h2><p>Use this only when money has actually arrived. Expenses are separate.</p><label>Outstanding sale<select required value={payBill} onChange={e=>setPayBill(e.target.value)}><option value="">Choose sale</option>{bills.filter(b=>b.outstanding>0).map(b=><option key={b.id} value={b.id}>{b.reference} · {b.partyName} · {rupees(b.outstanding)}</option>)}</select></label><div className="grid"><label>Payment date<input type="date" required max={today()} value={payDay} onChange={e=>setPayDay(e.target.value)}/></label><label>Received account<input list="ledger-accounts" required value={payAccount} onChange={e=>setPayAccount(e.target.value)}/></label><label>Received amount ₹<input required type="number" min="0.01" step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)}/></label></div><label>Payment note<input value={payNote} onChange={e=>setPayNote(e.target.value)}/></label><button disabled={busy}>Record payment</button></form>}
 </AppShell>;
}